apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-username: YWRtaW4=   # base64 encoded value of 'admin'
  mongodb-password: cGFzc3dvcmQxMjM=  # base64 encoded value of 'password123'
